# Generated by Django 2.0.3 on 2018-05-25 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_doc', models.CharField(default='', max_length=50)),
                ('ativo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bio', models.TextField(blank=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='user_photo')),
                ('doc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clientes.Documento')),
                ('produtos', models.ManyToManyField(blank=True, to='produtos.Produtos')),
            ],
        ),
    ]
